'use strict';
const $=id=>document.getElementById(id),C=window.MPS_CONFIG,PAGE=document.body.dataset.page;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const BUNDLED_FOLDERS=["2026mental2", "@growthai", "mps-report-showcase", "mps-football-centers", "20260916 맵", "2026physical", "Mtest", "haeonsports", "20260916 diary", "rnd", "mpsmanual", "2026growth", "mentalguide", "haeon", "mps-founding-operations", "mps-founding-brochure", "@nextlocal", "2026mpssports_football", "@HAEONEMR", "20260922mpssports"];
function bundledUrl(value){if(typeof value!=="string")return value;let v=value.replace(/^\.\.\/2026mental\//,"resources/2026mental2/");for(const folder of BUNDLED_FOLDERS){const prefix="../"+folder+"/";if(v.startsWith(prefix))return "resources/"+folder+"/"+v.slice(prefix.length)}return v}
function safeUrl(v){if(!v)return '';try{const u=new URL(v,location.href);return ['http:','https:'].includes(u.protocol)||(u.protocol==='file:'&&!/^[a-z]+:/i.test(v))?v:''}catch{return ''}}
const ext=(url,text,cls='button')=>safeUrl(url=bundledUrl(url))?`<a class="${cls}" href="${esc(url)}" target="_blank" rel="noopener">${esc(text)} ↗</a>`:'<span class="muted">연결 전</span>';
let data,loggedIn=false,storageAvailable=true,storageWarning='',orgFilter=document.querySelector('.org-panel')?.dataset.kind||'all',editingOrg=null,editingPlayer=null;
function validData(d){return d&&d.version===2&&Array.isArray(d.organizations)&&Array.isArray(d.players)&&d.organizations.every(o=>o&&typeof o.id==='string'&&typeof o.name==='string'&&Object.keys(C.types).includes(o.type)&&C.types[o.type].includes(o.subtype)&&typeof o.region==='string'&&['준비 중','운영 중','일시 중지'].includes(o.status)&&typeof o.dashboardActive==='boolean'&&typeof o.dashboardUrl==='string'&&(!o.dashboardActive||!!safeUrl(o.dashboardUrl))&&(!o.dashboardUrl||!!safeUrl(o.dashboardUrl))&&typeof o.sample==='boolean')&&new Set(d.organizations.map(x=>x.id)).size===d.organizations.length&&d.players.every(p=>p&&typeof p.id==='string'&&typeof p.name==='string'&&typeof p.active==='boolean'&&(p.mentalManaged===undefined||typeof p.mentalManaged==='boolean')&&typeof p.program==='string'&&typeof p.sample==='boolean'&&Array.isArray(p.orgIds)&&p.orgIds.every(id=>d.organizations.some(o=>o.id===id))&&p.reports&&C.reportFields.every(([k])=>typeof p.reports[k]==='string'&&(!p.reports[k]||!!safeUrl(p.reports[k]))))&&new Set(d.players.map(x=>x.id)).size===d.players.length}
function loadData(){let raw;try{raw=localStorage.getItem(C.storageKey);if(raw){const parsed=JSON.parse(raw);if(!validData(parsed))throw Error('invalid');return parsed}const old=localStorage.getItem('mps-basecamp-orgs-v1');if(old){const records=JSON.parse(old);if(Array.isArray(records)&&records.every(o=>o&&typeof o.id==='string'&&typeof o.name==='string'&&['Clinic','Center'].includes(o.type)&&typeof o.region==='string'&&['준비 중','운영 중','일시 중지'].includes(o.status))){const migrated={version:2,organizations:records.map(o=>({...o,subtype:C.types[o.type][o.type==='Clinic'?1:0],dashboardActive:false,dashboardUrl:'',contact:'',note:'',sample:o.id.startsWith('sample-')})),players:[]};localStorage.setItem(C.storageKey,JSON.stringify(migrated));return migrated}}const fresh=JSON.parse(JSON.stringify(C.seed));localStorage.setItem(C.storageKey,JSON.stringify(fresh));return fresh}catch{storageWarning=raw?'저장된 데이터를 읽지 못했습니다. 원본을 덮어쓰지 않도록 임시 샘플로 표시합니다. 백업을 확인한 후 가져오기를 사용하세요.':'브라우저 저장을 사용할 수 없습니다. 변경 사항은 현재 화면에만 남습니다.';storageAvailable=false;return JSON.parse(JSON.stringify(C.seed))}}
data=loadData();
function migrateResourceLinks(){let changed=false;for(const p of data.players)for(const k of Object.keys(p.reports)){const next=bundledUrl(p.reports[k]);if(next!==p.reports[k]){p.reports[k]=next;changed=true}}for(const o of data.organizations){const next=bundledUrl(o.dashboardUrl);if(next!==o.dashboardUrl){o.dashboardUrl=next;changed=true}}if(changed&&storageAvailable){try{localStorage.setItem(C.storageKey,JSON.stringify(data))}catch{}}}
migrateResourceLinks();
function toast(t){$('toast').textContent=t;$('toast').hidden=false;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('toast').hidden=true,4000)}
function save(){if(!loggedIn)return;data.updatedAt=new Date().toISOString();if(storageAvailable){try{localStorage.setItem(C.storageKey,JSON.stringify(data));toast('이 브라우저에 저장했습니다.')}catch{storageAvailable=false;storageWarning='저장 공간을 사용할 수 없습니다. 백업을 다운로드해 주세요.';toast(storageWarning)}}else toast('현재 화면에만 반영했습니다. 백업을 다운로드해 주세요.');render()}
function setSession(on){loggedIn=on;$('login').hidden=on;$('workspace').hidden=!on;if(on){render()}else{$('username').focus();document.querySelectorAll('dialog[open]').forEach(d=>d.close())}}
$('login-form').onsubmit=e=>{e.preventDefault();if($('username').value.trim()==='admin'&&$('password').value==='jw1824'){try{localStorage.setItem(C.authKey,'active');sessionStorage.setItem('mps-basecamp-session-v1','active')}catch{}$('password').value='';$('login-error').textContent='';setSession(true)}else{$('login-error').textContent='아이디 또는 비밀번호를 확인해 주세요.';$('password').focus()}};
$('show-password').onclick=()=>{const show=$('password').type==='password';$('password').type=show?'text':'password';$('show-password').textContent=show?'숨기기':'보기';$('show-password').setAttribute('aria-label',show?'비밀번호 숨기기':'비밀번호 표시')};
document.querySelectorAll('.logout').forEach(b=>b.onclick=()=>{try{localStorage.removeItem(C.authKey);sessionStorage.removeItem('mps-basecamp-session-v1')}catch{}setSession(false);$('login-form').reset();$('password').type='password';$('show-password').textContent='보기';window.scrollTo(0,0)});
window.addEventListener('storage',e=>{if(e.key===C.authKey){if(!e.newValue){try{sessionStorage.removeItem('mps-basecamp-session-v1')}catch{}}setSession(e.newValue==='active')}if(e.key===C.storageKey&&e.newValue){try{const d=JSON.parse(e.newValue);if(validData(d)){data=d;render();toast('다른 창의 변경 사항을 반영했습니다.')}}catch{}}});
function badge(text,on=false){return `<span class="badge ${on?'live':''}">${esc(text)}</span>`}
function stat(title,n,sub=''){return `<div class="metric"><span>${title}</span><b>${n}</b><small>${sub}</small></div>`}
function nameFor(id){return data.organizations.find(o=>o.id===id)?.name||'연결 해제'}
function isMentalPlayer(p){return typeof p.mentalManaged==='boolean'?p.mentalManaged:/멘탈|mental/i.test(p.program)}
function render(){if(!loggedIn)return;const players=data.players,orgs=data.organizations,active=players.filter(p=>p.active).length,totalSamples=orgs.filter(o=>o.sample).length+players.filter(p=>p.sample).length;
 if($('data-status'))$('data-status').textContent=storageWarning||`현재 브라우저 등록 자료 기준 · ${totalSamples?'샘플 '+totalSamples+'건 포함 · ':''}SportsMPS 실데이터 연동 전`;
 if($('summary-stats'))$('summary-stats').innerHTML=stat('등록 선수',players.length,'현재 목록 전체')+stat('활성 선수',active,'활성 상태로 설정한 선수')+stat('등록기관',orgs.length,'팀 · 클리닉 · 센터 합계')+stat('팀',orgs.filter(o=>o.type==='Team').length)+stat('클리닉',orgs.filter(o=>o.type==='Clinic').length)+stat('센터',orgs.filter(o=>o.type==='Center').length);
 if($('team-stats'))$('team-stats').innerHTML=stat('활성 선수',active,'현재 등록 선수 중')+stat('등록 팀',orgs.filter(o=>o.type==='Team').length)+stat('대시보드 활성 팀',orgs.filter(o=>o.type==='Team'&&o.dashboardActive&&safeUrl(o.dashboardUrl)).length);
 if($('mental-stats')){const managed=players.filter(isMentalPlayer);$('mental-stats').innerHTML=stat('멘탈 관리 선수',managed.length,'멘탈 관리 대상으로 지정')+stat('활성 선수',managed.filter(p=>p.active).length,'관리 선수 중 활성 상태')+stat('멘탈 리포트 연결',managed.filter(p=>p.reports.mental).length,'관리 선수 중 링크 등록')}
 renderOrgs();renderPlayers();if(['player','organization'].includes(PAGE))renderDetail();if(PAGE==='guide'&&!$('guide-root').children.length)renderGuide();
}
function renderOrgs(){if(!$('org-rows'))return;const q=$('org-search').value.trim().toLowerCase();const list=data.organizations.filter(o=>(orgFilter==='all'||o.type===orgFilter)&&`${o.name} ${o.region}`.toLowerCase().includes(q));$('org-rows').innerHTML=list.map(o=>`<tr><td><a class="row-link" href="organization.html?id=${encodeURIComponent(o.id)}" target="_blank" rel="noopener">${esc(o.name)} ↗</a>${o.sample?'<small class="sample-label">샘플</small>':''}</td><td>${esc(o.type)}<small>${esc(o.subtype)}</small></td><td>${esc(o.region)}</td><td>${badge(o.status,o.status==='운영 중')}</td><td>${o.dashboardActive&&safeUrl(o.dashboardUrl)?ext(o.dashboardUrl,o.type==='Team'?'팀 대시보드':'열기','text-link'):badge('미활성')}</td><td><button class="text-link" data-edit-org="${esc(o.id)}">수정 ↗</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">등록된 기관 또는 검색 결과가 없습니다. 기관 등록으로 시작하세요.</td></tr>';document.querySelectorAll('[data-org-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.orgFilter===orgFilter)));}
function renderPlayers(){if(!$('player-rows'))return;const q=$('player-search').value.trim().toLowerCase(),f=$('player-filter').value;const list=data.players.filter(p=>(PAGE!=='mental'||isMentalPlayer(p))&&(f==='all'||(f==='active')===p.active)&&`${p.name} ${p.program}`.toLowerCase().includes(q));$('player-rows').innerHTML=list.map(p=>`<tr><td><a class="row-link" href="player.html?id=${encodeURIComponent(p.id)}" target="_blank" rel="noopener">${esc(p.name)} ↗</a>${p.sample?'<small class="sample-label">샘플</small>':''}</td><td>${badge(p.active?'활성':'비활성',p.active)}</td><td>${esc(p.program)||'미등록'}</td><td>${p.orgIds.map(id=>`<small>${esc(nameFor(id))}</small>`).join('')||'미등록'}</td><td><button class="text-link" data-edit-player="${esc(p.id)}">수정 ↗</button></td></tr>`).join('')||'<tr><td colspan="5" class="empty">등록된 선수 또는 검색 결과가 없습니다. 선수 등록으로 시작하세요.</td></tr>';}
$('org-search')?.addEventListener('input',renderOrgs);$('player-search')?.addEventListener('input',renderPlayers);$('player-filter')?.addEventListener('change',renderPlayers);
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||!loggedIn)return;if(b.hasAttribute('data-org-filter')){orgFilter=b.dataset.orgFilter;renderOrgs()}if(b.hasAttribute('data-add-org'))openOrg();if(b.hasAttribute('data-edit-org'))openOrg(data.organizations.find(o=>o.id===b.dataset.editOrg));if(b.hasAttribute('data-add-player'))openPlayer();if(b.hasAttribute('data-edit-player'))openPlayer(data.players.find(p=>p.id===b.dataset.editPlayer));if(b.hasAttribute('data-close-dialog'))b.closest('dialog').close()});
function dialog(id,title,fields,deleteButton){$('dialogs').innerHTML=`<dialog id="${id}"><form><div class="dialog-heading"><h2>${title}</h2><button type="button" data-close-dialog aria-label="닫기">✕</button></div>${fields}<p class="form-error" role="alert"></p><div class="dialog-actions">${deleteButton?'<button type="button" class="danger" id="delete-record">삭제</button>':''}<button type="button" class="button" data-close-dialog>취소</button><button type="submit" class="primary">저장하기</button></div></form></dialog>`;$(id).showModal();return $(id).querySelector('form')}
function field(label,id,value='',type='text',required=false){return `<label for="${id}">${label}</label><input id="${id}" name="${id}" type="${type}" value="${esc(value)}" ${required?'required':''} maxlength="500">`}
function openOrg(org){editingOrg=org?.id||null;const type=org?.type||(orgFilter==='all'?'Clinic':orgFilter);const fields=field('기관명','org-name',org?.name||'','text',true)+`<div class="field-grid"><div><label for="org-type">구분</label><select id="org-type">${Object.keys(C.types).map(t=>`<option ${type===t?'selected':''}>${t}</option>`).join('')}</select></div><div><label for="org-subtype">기관 유형</label><select id="org-subtype"></select></div></div>`+field('지역','org-region',org?.region||'','text',true)+`<label for="org-status">운영 상태</label><select id="org-status">${['준비 중','운영 중','일시 중지'].map(t=>`<option ${org?.status===t?'selected':''}>${t}</option>`).join('')}</select><label class="check"><input id="org-dashboard-active" type="checkbox" ${org?.dashboardActive?'checked':''}> 대시보드 활성화</label>`+field('해당 기관 대시보드 주소 (https://...)','org-url',org?.dashboardUrl||'')+field('담당자 · 연락 메모','org-contact',org?.contact||'')+`<label for="org-note">운영 메모</label><textarea id="org-note" rows="3" maxlength="3000">${esc(org?.note||'')}</textarea><label class="check"><input id="org-sample" type="checkbox" ${org?.sample?'checked':''}> 샘플 데이터로 표시</label>`;
 const form=dialog('org-dialog',org?'기관 수정':'기관 등록',fields,!!org);const fillSub=()=>{$('org-subtype').innerHTML=C.types[$('org-type').value].map(t=>`<option ${org?.subtype===t?'selected':''}>${t}</option>`).join('')};fillSub();$('org-type').onchange=fillSub;
 form.onsubmit=e=>{e.preventDefault();const name=$('org-name').value.trim(),region=$('org-region').value.trim(),url=$('org-url').value.trim(),active=$('org-dashboard-active').checked;if(!name||!region){form.querySelector('.form-error').textContent='기관명과 지역을 입력해 주세요.';return}if((url&&!safeUrl(url))||(active&&!url)){form.querySelector('.form-error').textContent='대시보드를 활성화하려면 올바른 http(s) 주소 또는 로컬 페이지 경로를 입력해 주세요.';return}const value={id:editingOrg||newId('org'),name,type:$('org-type').value,subtype:$('org-subtype').value,region,status:$('org-status').value,dashboardActive:active,dashboardUrl:url,contact:$('org-contact').value.trim(),note:$('org-note').value.trim(),sample:$('org-sample').checked};data.organizations=editingOrg?data.organizations.map(o=>o.id===editingOrg?value:o):[...data.organizations,value];$('org-dialog').close();save()};
 if(org)$('delete-record').onclick=()=>{const linked=data.players.filter(p=>p.orgIds.includes(org.id)).length;if(confirm(`이 기관을 삭제할까요?${linked?' 연결된 선수 '+linked+'명의 소속에서도 해제됩니다.':''}`)){data.organizations=data.organizations.filter(o=>o.id!==org.id);data.players.forEach(p=>p.orgIds=p.orgIds.filter(id=>id!==org.id));$('org-dialog').close();save()}};
}
function newId(prefix){return prefix+'-'+(globalThis.crypto?.randomUUID?.()||Date.now()+'-'+Math.random().toString(36).slice(2))}
function openPlayer(player){editingPlayer=player?.id||null;let fields=field('선수명','player-name',player?.name||'','text',true)+`<label class="check"><input type="checkbox" id="player-active" ${player?.active!==false?'checked':''}> 활성 선수</label>`+field('현재 진행 프로그램','player-program',player?.program||'')+`<label class="check"><input type="checkbox" id="player-mental" ${player?isMentalPlayer(player)?'checked':'':PAGE==='mental'?'checked':''}> 멘탈 관리 대상</label>`+'<fieldset><legend>소속 팀 · 클리닉 · 센터 (복수 선택)</legend>'+data.organizations.map(o=>`<label class="check"><input type="checkbox" name="orgIds" value="${esc(o.id)}" ${player?.orgIds.includes(o.id)?'checked':''}>${esc(o.name)} <small>${esc(o.type)}</small></label>`).join('')+(!data.organizations.length?'<p class="muted">기관을 먼저 등록해 주세요.</p>':'')+'</fieldset><details><summary>선수별 리포트 주소 연결</summary><p class="muted">해당 선수의 실제 리포트 주소를 붙여넣으세요. 비어 있는 항목은 연결 전으로 표시됩니다.</p>'+C.reportFields.map(([k,t])=>field(t,'report-'+k,player?.reports[k]||'')).join('')+'</details><label for="player-note">관리 메모</label><textarea id="player-note" rows="3" maxlength="3000">'+esc(player?.note||'')+'</textarea><label class="check"><input type="checkbox" id="player-sample" '+(player?.sample?'checked':'')+'> 샘플 데이터로 표시</label>';
 const form=dialog('player-dialog',player?'선수 수정':'선수 등록',fields,!!player);form.onsubmit=e=>{e.preventDefault();const name=$('player-name').value.trim();if(!name){form.querySelector('.form-error').textContent='선수명을 입력해 주세요.';return}const reports=Object.fromEntries(C.reportFields.map(([k])=>[k,$('report-'+k).value.trim()]));if(Object.values(reports).some(u=>u&&!safeUrl(u))){form.querySelector('.form-error').textContent='리포트 주소는 http(s) 주소 또는 로컬 페이지 경로로 입력해 주세요.';return}const value={id:editingPlayer||newId('player'),name,active:$('player-active').checked,program:$('player-program').value.trim(),mentalManaged:$('player-mental').checked,orgIds:[...form.querySelectorAll('[name=orgIds]:checked')].map(x=>x.value),reports,note:$('player-note').value.trim(),sample:$('player-sample').checked};data.players=editingPlayer?data.players.map(p=>p.id===editingPlayer?value:p):[...data.players,value];$('player-dialog').close();save()};if(player)$('delete-record').onclick=()=>{if(confirm('이 선수를 목록에서 삭제할까요? 연결된 원본 리포트는 삭제하지 않습니다.')){data.players=data.players.filter(p=>p.id!==player.id);$('player-dialog').close();save()}};
}
function renderDetail(){const id=new URLSearchParams(location.search).get('id');const isPlayer=PAGE==='player',item=(isPlayer?data.players:data.organizations).find(x=>x.id===id);if(!item){$('detail-content').innerHTML='<h1>등록 정보를 찾을 수 없습니다.</h1><p class="muted">같은 브라우저에서 등록한 자료인지 확인해 주세요.</p><a class="button" href="index.html">종합 관리로</a>';return}let html=`<a class="back-link" href="${isPlayer?'athletes.html':'index.html'}">← 목록으로</a><div class="page-heading"><div><span class="eyebrow">${isPlayer?'PLAYER PROFILE':esc(item.type)}</span><h1>${esc(item.name)}</h1>${item.sample?badge('샘플 데이터'):''}</div><button class="primary" data-edit-${isPlayer?'player':'org'}="${esc(id)}">정보 수정 ↗</button></div>`;
 if(isPlayer){html+=`<div class="panel narrative"><h3>현재 프로그램</h3><p>${esc(item.program)||'프로그램 등록 전'}</p>${badge(item.active?'활성 선수':'비활성 선수',item.active)}</div><section class="section"><h2>소속기관</h2><div class="resource-grid">${item.orgIds.map(oid=>{const o=data.organizations.find(o=>o.id===oid);return `<a class="resource" href="organization.html?id=${encodeURIComponent(oid)}"><span class="eyebrow">${esc(o.type)} · ${esc(o.subtype)}</span><h3>${esc(o.name)}</h3><p>${esc(o.region)} · ${esc(o.status)}</p></a>`}).join('')||'<p class="muted">연결된 소속기관이 없습니다.</p>'}</div></section><section class="section"><h2>선수 리포트</h2><p class="muted">${item.sample?'샘플 선수의 예시 자료입니다. 실제 선수의 검사 결과가 아닙니다.':'선수별로 등록한 리포트 주소입니다.'}</p><div class="form-links">${C.reportFields.map(([k,t])=>item.reports[k]?ext(item.reports[k],t):`<div class="button muted">${t} · 연결 전</div>`).join('')}</div></section>`}else{const linked=data.players.filter(p=>p.orgIds.includes(id));html+=`<div class="panel narrative"><div class="chips">${badge(item.subtype)}${badge(item.status,item.status==='운영 중')}</div><p>지역 · ${esc(item.region)}</p><p>담당 · ${esc(item.contact)||'미등록'}</p>${item.dashboardActive?ext(item.dashboardUrl,'해당 기관 대시보드','primary inline'):'<p class="muted">대시보드 미활성 · 수정에서 주소를 등록하고 활성화할 수 있습니다.</p>'}</div><section class="section"><h2>소속 선수 ${linked.length}명</h2><div class="resource-grid">${linked.map(p=>`<a class="resource" href="player.html?id=${encodeURIComponent(p.id)}"><h3>${esc(p.name)} ↗</h3><p>${esc(p.program)}</p>${badge(p.active?'활성':'비활성',p.active)}</a>`).join('')||'<p class="muted">연결된 선수가 없습니다.</p>'}</div></section>`}html+=`<section class="section panel narrative"><h3>관리 메모</h3><p class="preserve">${esc(item.note)||'등록된 메모가 없습니다.'}</p></section>`;$('detail-content').innerHTML=html;
}
$('export-data')?.addEventListener('click',()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='MPS-basecamp-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
$('import-data')?.addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>5e6)throw Error();const incoming=JSON.parse(await file.text());if(!validData(incoming))throw Error();if(confirm(`기관 ${incoming.organizations.length}곳, 선수 ${incoming.players.length}명으로 현재 목록을 교체할까요? 먼저 백업을 권장합니다.`)){data=incoming;storageAvailable=true;storageWarning='';migrateResourceLinks();save()}}catch{toast('가져올 수 없는 백업입니다. 형식·중복 ID·기관 연결·주소를 확인해 주세요.')}e.target.value=''});
let guideIndex=0;
function renderGuide(){const key=new URLSearchParams(location.search).get('kind')||'mobile',guide=window.MPS_GUIDES[key];if(!guide){$('guide-root').innerHTML='<h1>가이드를 찾을 수 없습니다.</h1><a href="index.html#reports">리포트 모음으로</a>';return}guideIndex=Math.max(0,Math.min(guide.pages.length-1,Math.floor(Number(new URLSearchParams(location.search).get('page')||1))-1));if(!Number.isFinite(guideIndex))guideIndex=0;
 $('guide-root').innerHTML=`<a class="back-link" href="${key==='team'?'athletes.html':key==='clinic'?'clinic.html':key==='center'?'center.html':key==='mental-program'?'mental.html':'index.html#reports'}">← 목록으로</a><div class="page-heading"><div><span class="eyebrow">BASECAMP EXPLAINER</span><h1>${esc(guide.title)}</h1><p class="muted">${esc(guide.description)}</p></div>${ext(guide.source,'원본 열기')}</div><div class="guide-toolbar"><button id="guide-prev" class="button">← 이전</button><label for="guide-select" class="sr-only">설명할 페이지</label><select id="guide-select">${guide.pages.map((p,i)=>`<option value="${i}">${i+1}. ${esc(p.title)}</option>`).join('')}</select><button id="guide-next" class="button">다음 →</button><span id="guide-count"></span></div><div id="guide-page"></div><p class="source-note">${esc(guide.sourceNote||'기존 MPS 자료를 바탕으로 구성한 설명 가이드입니다.')} ${guide.evidence?ext(guide.evidence,'용어 참고 자료','text-link'):''}</p>`;
 const show=()=>{const p=guide.pages[guideIndex];$('guide-select').value=guideIndex;$('guide-prev').disabled=guideIndex===0;$('guide-next').disabled=guideIndex===guide.pages.length-1;$('guide-count').textContent=`${guideIndex+1} / ${guide.pages.length}`;const visual=p.image?`<a href="${esc(p.image)}" target="_blank" rel="noopener" aria-label="${esc(p.title)} 화면 확대"><img src="${esc(p.image)}" alt="${esc(p.title)} 실제 샘플 화면"></a>`:`<div class="workflow-visual"><span class="eyebrow">WORKFLOW / ${String(guideIndex+1).padStart(2,'0')}</span><h2>${esc(p.title)}</h2>${p.steps.map((s,i)=>`<div><span>${i+1}</span>${esc(s)}</div>`).join('')}</div>`;$('guide-page').innerHTML=`<div class="guide-layout ${guide.mobile?'mobile-guide':''}"><div class="guide-visual">${visual}${p.image?'<small>이미지를 누르면 원본 크기로 열립니다.</small>':''}</div><aside class="guide-notes"><span class="eyebrow">${esc(guide.audience||'부모님 설명용')}</span><h2>${esc(p.title)}</h2><p class="guide-summary">${esc(p.summary)}</p><h3>이 순서로 읽어주세요</h3><ol>${p.read.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><h3>쉬운 용어</h3><dl>${p.terms.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl><div class="say-box"><span>이렇게 설명해 보세요</span><p>“${esc(p.say)}”</p></div><div class="check-box"><b>팀원이 기억할 점</b><p>${esc(p.check)}</p></div></aside></div>`;};
 const go=n=>{guideIndex=Math.max(0,Math.min(guide.pages.length-1,n));const u=new URL(location.href);u.searchParams.set('page',guideIndex+1);history.replaceState(null,'',u);show();$('guide-page').scrollIntoView({block:'start'})};$('guide-prev').onclick=()=>go(guideIndex-1);$('guide-next').onclick=()=>go(guideIndex+1);$('guide-select').onchange=e=>go(Number(e.target.value));document.addEventListener('keydown',e=>{if(!loggedIn||['INPUT','TEXTAREA','SELECT','BUTTON','A'].includes(e.target.tagName)||document.querySelector('dialog[open]'))return;if(e.key==='ArrowRight'){e.preventDefault();go(guideIndex+1)}if(e.key==='ArrowLeft'){e.preventDefault();go(guideIndex-1)}});show();
}
try{const active=localStorage.getItem(C.authKey)==='active'||sessionStorage.getItem('mps-basecamp-session-v1')==='active';if(active)localStorage.setItem(C.authKey,'active');setSession(active)}catch{setSession(false)}
