'use strict';
const HQ_KEY='mps-basecamp-hq-v1';
function validHQ(v){if(!v||typeof v!=="object")return false;const shapes={sessions:['id','playerId','date','coach','note','next'],events:['id','date','time','owner','title'],links:['id','from','to','note','date'],ideas:['id','title','owner','next','status'],referrals:['id','playerId','clinicId','reason','centerId','date','status'],comments:['id','playerId','clinicId','date','author','text']};return Object.entries(shapes).every(([k,fields])=>Array.isArray(v[k])&&v[k].every(x=>x&&fields.every(f=>typeof x[f]==='string')))&&['chats','diaries'].every(k=>v[k]&&typeof v[k]==='object'&&!Array.isArray(v[k])&&Object.values(v[k]).every(x=>typeof x==='string'))}
let hq;
try{hq=JSON.parse(localStorage.getItem(HQ_KEY)||'null')||{sessions:[],events:[],links:[],ideas:[],referrals:[],comments:[],chats:{},diaries:{}}}catch{hq=null}
if(hq&&!validHQ(hq))hq=null;
const today=()=>new Date().toLocaleDateString('en-CA');
const listOpts=(items)=>items.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');
const playerLink=p=>`<a class="row-link" href="player.html?id=${encodeURIComponent(p.id)}">${esc(p.name)} · ${esc(p.number||p.id)} →</a>`;
function persistHQ(){if(!hq)return false;try{localStorage.setItem(HQ_KEY,JSON.stringify(hq));toast('저장했습니다 · 현재 브라우저');return true}catch{toast('저장하지 못했습니다. 브라우저 저장 공간을 확인하세요.');return false}}
function role(){return sessionStorage.getItem('mps-role')||'admin'}
function mentorPage(){return PAGE.startsWith('mental')||['player','calendar','forms','guide','surveys'].includes(PAGE)}
window.hqAllowed=()=>role()!=='mps'||mentorPage();
window.applyHQGate=function(){
 if(!loggedIn)return;
 const account=document.querySelector('.account>span:nth-child(2)');if(account)account.innerHTML=esc(role())+'<small>'+ (role()==='mps'?'멘토링 담당':'Basecamp 구성원')+'</small>';
 document.querySelectorAll('.sidebar nav a').forEach(a=>{a.hidden=role()==='mps'&&!/mental|reports/.test(a.getAttribute('href'))});
 if(role()==='mps'){const reports=document.querySelector('.sidebar a[href="index.html#reports"]');if(reports)reports.href='guide.html?kind=mental';const back=document.querySelector('#detail-content .back-link');if(back)back.href='mental.html'}
 let type=!hqAllowed()?'denied':PAGE==='players'&&!sessionStorage.getItem('mps-players-unlock')?'players':PAGE.startsWith('mental')&&role()!=='mps'&&!sessionStorage.getItem('mps-mentor-unlock')?'mentor':PAGE==='player'&&!sessionStorage.getItem('mps-players-unlock')&&!sessionStorage.getItem('mps-mentor-unlock')&&role()!=='mps'?'players':'';
 let gate=$('hq-gate');if(!type){gate?.remove();document.querySelector('.content').hidden=false;return}
 document.querySelector('.content').hidden=true;if(gate)return;
 gate=document.createElement('section');gate.id='hq-gate';gate.className='gate-panel';document.querySelector('main').append(gate);
 if(type==='denied'){gate.innerHTML='<h1>멘토 전용 계정입니다</h1><p>담당 선수와 멘토링 업무 화면으로 이동해 주세요.</p><a class="primary" href="mental.html">멘탈퍼포먼스 →</a>';return}
 gate.innerHTML=`<span class="eyebrow">ADDITIONAL ACCESS</span><h1>${type==='mentor'?'멘토링 권한 확인':'전체 선수 · 추가 확인'}</h1><p class="muted">${type==='mentor'?'멘토 계정으로 한 번 더 확인합니다.':'선수 관리 영역에 진입하려면 아이디와 비밀번호를 다시 입력하세요.'}</p><form id="gate-form"><label>아이디<input name="user" autocomplete="username" required></label><label>비밀번호<input name="password" type="password" autocomplete="current-password" required></label><p id="gate-error" role="alert"></p><button class="primary">확인 후 입장 →</button></form><p class="tiny">임시 화면 접근 확인 · 서버 권한 관리는 API 연결 예정</p>`;
 $('gate-form').onsubmit=e=>{e.preventDefault();const f=e.target;if(f.user.value.trim()===(type==='mentor'?'mps':'admin')&&f.password.value==='1824'){sessionStorage.setItem(type==='mentor'?'mps-mentor-unlock':'mps-players-unlock','yes');gate.remove();document.querySelector('.content').hidden=false;render()}else $('gate-error').textContent='아이디 또는 비밀번호를 확인해 주세요.'};
};
function mount(id,html){if($(id))$(id).innerHTML=html}
let weeklyPage=0;
function renderWeekly(){if(!$('weekly-list')||!hq)return;const ids=new Set(hq.sessions.map(s=>s.playerId)),q=$('weekly-search')?.value||'';const ps=data.players.filter(p=>ids.has(p.id)&&`${p.name} ${p.number||p.id}`.includes(q));weeklyPage=Math.min(weeklyPage,Math.max(0,Math.ceil(ps.length/10)-1));mount('weekly-list',`<input id="weekly-search" placeholder="선수명 · 고유번호 검색" value="${esc(q)}"><div class="weekly-names">${ps.slice(weeklyPage*10,weeklyPage*10+10).map(playerLink).join('')||'<p class="muted">저장된 멘토링 회차가 아직 없습니다.</p>'}</div><div class="resource-actions"><button class="button" id="week-prev" ${weeklyPage===0?'disabled':''}>이전</button><span>${weeklyPage+1} / ${Math.max(1,Math.ceil(ps.length/10))} · 총 ${ps.length}명</span><button class="button" id="week-next" ${(weeklyPage+1)*10>=ps.length?'disabled':''}>다음</button></div>`);$('week-prev').onclick=()=>{weeklyPage--;renderWeekly()};$('week-next').onclick=()=>{weeklyPage++;renderWeekly()};$('weekly-search').onchange=renderWeekly}
function renderSessions(){if(PAGE!=='player'||!hq)return;const p=data.players.find(p=>p.id===new URLSearchParams(location.search).get('id'));if(!p)return;let box=$('mentoring-chart');if(!box){box=document.createElement('section');box.id='mentoring-chart';box.className='section';$('detail-content').append(box)}const sessions=hq.sessions.filter(s=>s.playerId===p.id).sort((a,b)=>b.date.localeCompare(a.date));
 box.innerHTML=`<div class="section-heading"><div><span class="eyebrow">MENTORING CHART</span><h2>${esc(p.name)} · ${esc(p.number||p.id)}</h2><p class="muted">담당 ${esc(p.coach||'미지정')} · 멘토링 ${sessions.length}회</p></div><button class="primary" id="add-session">+ 회차 기록</button></div><div class="chart-columns"><article class="panel narrative"><h3>회차별 상담 기록</h3><div class="session-timeline">${sessions.map((s,i)=>`<article><b>${sessions.length-i}회 · ${esc(s.date)}</b><small>${esc(s.coach||'담당 미지정')}</small><p class="preserve">${esc(s.note)}</p><p>다음 행동 · ${esc(s.next||'미등록')}</p><button class="text-link" data-session-edit="${esc(s.id)}">기록 수정</button></article>`).join('')||'<p class="muted">첫 상담 내용을 저장하면 주간 미팅 명단에 자동으로 포함됩니다.</p>'}</div></article><aside class="panel narrative"><h3>다이어리 · 함께 읽기</h3><p>${p.diaryUrl?ext(p.diaryUrl,'선수 다이어리'):'선수별 다이어리 주소 미등록 · 정보 수정에서 연결하세요.'}</p><a class="button" href="resources/20260916 diary/index.html" target="_blank" rel="noopener">공통 다이어리 도구 ↗</a><label for="diary-note">선수와 공유한 다이어리 내용</label><textarea id="diary-note" rows="6" placeholder="선수가 공유한 기록을 붙여넣으세요.">${esc(hq.diaries[p.id]||'')}</textarea><button class="button" id="save-diary">다이어리 메모 저장</button><hr><h3>AI 멘탈 · 다이어리 통합 판독</h3><p class="muted">API 연결 대기 · 리포트 URL, 회차 기록, 공유 다이어리를 요청서로 준비합니다. 현재 AI 판독은 실행되지 않습니다.</p><button class="button" id="prepare-ai">전체 AI 요약 · 판독 요청서 만들기</button><textarea id="ai-request" rows="8" readonly hidden aria-label="AI 판독 요청서"></textarea></aside></div>`;
 $('save-diary').onclick=()=>{hq.diaries[p.id]=$('diary-note').value;persistHQ()};$('add-session').onclick=()=>editSession(p);box.querySelectorAll('[data-session-edit]').forEach(x=>x.onclick=()=>editSession(p,hq.sessions.find(s=>s.id===x.dataset.sessionEdit)));
 $('prepare-ai').onclick=()=>{const text=`[AI 연결용 요청 초안 · 미실행]\n선수: ${p.name} (${p.number||p.id})\n기본 메모: ${p.note||''}\n리포트 주소(내용 자동 수집 전):\n${JSON.stringify(p.reports,null,2)}\n멘토링 기록:\n${sessions.map(s=>`${s.date} / ${s.coach}\n${s.note}\n다음 행동: ${s.next}`).join('\n\n')}\n공유 다이어리:\n${hq.diaries[p.id]||'미등록'}\n요청: 기록 근거를 구분해 변화와 다음 상담 질문을 요약. 진단과 미래 성과를 단정하지 말 것.`;$('ai-request').hidden=false;$('ai-request').value=text};
}
function editSession(p,s){const form=dialog('session-dialog',s?'회차 기록 수정':'새 멘토링 회차',field('상담일','session-date',s?.date||today(),'date',true)+field('담당 멘토','session-coach',s?.coach||p.coach||'')+'<label>상담 기록<textarea id="session-note" rows="6" required maxlength="12000">'+esc(s?.note||'')+'</textarea></label>'+field('다음 행동','session-next',s?.next||''),false);form.onsubmit=e=>{e.preventDefault();if(!$('session-note').value.trim())return;const v={id:s?.id||newId('session'),playerId:p.id,date:$('session-date').value,coach:$('session-coach').value.trim(),note:$('session-note').value.trim(),next:$('session-next').value.trim(),savedAt:new Date().toISOString()};hq.sessions=s?hq.sessions.map(x=>x.id===s.id?v:x):[...hq.sessions,v];if(persistHQ()){$('session-dialog').close();renderSessions()}}}
function renderNetwork(){if(!$('network-manager')||!hq)return;mount('network-manager',`<form id="network-form" class="inline-form"><label>기관 A<select name="from" required>${listOpts(data.organizations)}</select></label><label>기관 B<select name="to" required>${listOpts(data.organizations)}</select></label><label>연결 내용<input name="note" placeholder="대표 소개 · 협업 내용"></label><button class="primary">연결 등록</button></form><div class="record-list">${hq.links.map(l=>`<div><b>${esc(nameFor(l.from))} ↔ ${esc(nameFor(l.to))}</b><p>${esc(l.note)} · ${esc(l.date)}</p><button class="text-link" data-remove-link="${esc(l.id)}">연결 해제</button></div>`).join('')||'<p class="muted">본부에서 연결한 기관 관계를 등록하세요.</p>'}</div>`);$('network-form').onsubmit=e=>{e.preventDefault();const f=e.target;if(f.from.value===f.to.value)return toast('서로 다른 기관을 선택하세요.');hq.links.push({id:newId('link'),from:f.from.value,to:f.to.value,note:f.note.value,date:today()});persistHQ();renderNetwork()};document.querySelectorAll('[data-remove-link]').forEach(b=>b.onclick=()=>{hq.links=hq.links.filter(l=>l.id!==b.dataset.removeLink);persistHQ();renderNetwork()})}
function renderCalendar(){if(!$('calendar-root')||!hq)return;const day=$('event-day')?.value||today();mount('calendar-root',`<label>조회 날짜<input id="event-day" type="date" value="${day}"></label><form id="event-form" class="inline-form"><label>시간<input name="time" type="time" required></label><label>기관 / 담당<input name="owner" required></label><label>일정 · 특이사항<input name="title" required></label><label>본부 공유 요청<input name="share" type="checkbox"></label><button class="primary">일정 저장</button></form><div class="record-list">${hq.events.filter(e=>e.date===day).sort((a,b)=>a.time.localeCompare(b.time)).map(e=>`<div><b>${esc(e.time)} · ${esc(e.title)}</b><p>${esc(e.owner)} · ${e.share?'본부 공유 요청 표시 / 미전송':'내부 일정'}</p><button class="text-link" data-event-delete="${esc(e.id)}">일정 삭제</button></div>`).join('')||'<p>이 날짜에 등록된 일정이 없습니다.</p>'}</div>`);$('event-day').onchange=renderCalendar;$('event-form').onsubmit=e=>{e.preventDefault();const f=e.target;hq.events.push({id:newId('event'),date:day,time:f.time.value,owner:f.owner.value,title:f.title.value,share:f.share.checked});persistHQ();renderCalendar()};document.querySelectorAll('[data-event-delete]').forEach(b=>b.onclick=()=>{hq.events=hq.events.filter(e=>e.id!==b.dataset.eventDelete);persistHQ();renderCalendar()})}
function renderProjects(){if(!$('project-board')||!hq)return;mount('chat-manager',`<form id="chats-form" class="inline-form">${['클리닉','센터','팀'].map(t=>`<label>${t} 오픈채팅 주소<input name="${t}" type="url" value="${esc(hq.chats[t]||'')}" placeholder="https://..."></label>`).join('')}<button class="button">주소 저장</button></form><div class="form-links">${Object.entries(hq.chats).filter(([,v])=>safeUrl(v)).map(([k,v])=>ext(v,k+' 채팅방')).join('')}</div>`);$('chats-form').onsubmit=e=>{e.preventDefault();hq.chats=Object.fromEntries(new FormData(e.target));persistHQ();renderProjects()};mount('project-board',`<form id="idea-form" class="inline-form"><label>아이디어<input name="title" required></label><label>담당자<input name="owner"></label><label>다음 행동<input name="next"></label><button class="primary">아이디어 등록</button></form><div class="record-list">${hq.ideas.map(i=>`<div><b>${esc(i.title)}</b><p>${esc(i.owner)} · ${esc(i.next)}</p><select data-idea="${esc(i.id)}" aria-label="아이디어 상태">${['아이디어','준비 중','진행 중','완료'].map(x=>`<option ${i.status===x?'selected':''}>${x}</option>`).join('')}</select></div>`).join('')}</div>`);$('idea-form').onsubmit=e=>{e.preventDefault();hq.ideas.push({id:newId('idea'),...Object.fromEntries(new FormData(e.target)),status:'아이디어'});persistHQ();renderProjects()};document.querySelectorAll('[data-idea]').forEach(s=>s.onchange=()=>{hq.ideas.find(i=>i.id===s.dataset.idea).status=s.value;persistHQ()})}
function renderPortals(){if(!hq)return;const id=$('doctor-root')?'doctor-root':$('center-players')?'center-players':null;if(!id)return;const type=id==='doctor-root'?'Clinic':'Center',org=$('portal-org')?.value||data.organizations.find(o=>o.type===type)?.id||'';const players=data.players.filter(p=>p.orgIds.includes(org));mount(id,`<label>기관<select id="portal-org">${listOpts(data.organizations.filter(o=>o.type===type))}</select></label><div class="record-list">${players.map(p=>`<div>${playerLink(p)}<p>${esc(p.program)}</p>${hq.comments.filter(c=>c.playerId===p.id).map(c=>`<div class="doctor-comment"><b>${esc(c.author)} · ${esc(c.date)}</b><p>${esc(c.text)}</p></div>`).join('')||'<small>팀닥터 코멘트 미등록</small>'}${type==='Clinic'?`<button class="button" data-doctor="${esc(p.id)}">코멘트 남기기</button>`:''}</div>`).join('')||'<p>소속 선수가 없습니다. 선수 정보 수정에서 소속기관을 연결하세요.</p>'}</div>`);$('portal-org').value=org;$('portal-org').onchange=renderPortals;document.querySelectorAll('[data-doctor]').forEach(b=>b.onclick=()=>{const f=dialog('doctor-dialog','팀닥터 코멘트',field('의료진 이름','doctor-author','','text',true)+'<label>컨디셔닝 코멘트<textarea id="doctor-text" required></textarea></label>',false);f.onsubmit=e=>{e.preventDefault();hq.comments.push({id:newId('comment'),playerId:b.dataset.doctor,clinicId:org,date:today(),author:$('doctor-author').value,text:$('doctor-text').value});persistHQ();$('doctor-dialog').close();renderPortals()}});
 if($('referral-root')){mount('referral-root',`<form id="referral-form" class="inline-form"><label>선수<select name="playerId" required>${listOpts(players)}</select></label><label>희망 클리닉<select name="clinicId" required>${listOpts(data.organizations.filter(o=>o.type==='Clinic'))}</select></label><label>요청 내용<input name="reason" required></label><button class="primary">본부 요청 등록</button></form><div class="record-list">${hq.referrals.map(r=>`<div><b>${esc(data.players.find(p=>p.id===r.playerId)?.name||'삭제된 선수')} → ${esc(nameFor(r.clinicId))}</b><p>${esc(r.reason)} · ${esc(r.status)} · ${esc(r.date)}</p><select data-referral="${esc(r.id)}" aria-label="본부 처리 상태">${['본부 접수','본부 검토 중','클리닉 연결 완료'].map(x=>`<option ${r.status===x?'selected':''}>${x}</option>`).join('')}</select></div>`).join('')}</div>`);$('referral-form').onsubmit=e=>{e.preventDefault();hq.referrals.push({id:newId('referral'),...Object.fromEntries(new FormData(e.target)),centerId:org,date:today(),status:'본부 접수'});persistHQ();renderPortals()};document.querySelectorAll('[data-referral]').forEach(s=>s.onchange=()=>{hq.referrals.find(r=>r.id===s.dataset.referral).status=s.value;persistHQ()})}}
window.renderHQ=function(){applyHQGate();if(!hq){toast('업무 저장 데이터를 읽지 못했습니다. 기존 자료는 덮어쓰지 않습니다.');return}if(document.querySelector('.content').hidden)return;renderWeekly();renderSessions();renderNetwork();renderCalendar();renderProjects();renderPortals();renderHQReferrals()};
$('team-age')?.addEventListener('change',renderOrgs);$('coach-filter')?.addEventListener('input',renderPlayers);
if($('common-form')){let draft;try{draft=JSON.parse(localStorage.getItem('mps-form-draft')||'null')}catch{}if(draft)for(const [k,v]of Object.entries(draft))if($('common-form').elements[k])$('common-form').elements[k].value=v;$('common-form').onsubmit=e=>{e.preventDefault();try{localStorage.setItem('mps-form-draft',JSON.stringify(Object.fromEntries(new FormData(e.target))));$('form-status').textContent='저장했습니다 · '+today()}catch{$('form-status').textContent='저장하지 못했습니다.'}}}
window.addEventListener('storage',e=>{if(e.key===HQ_KEY){try{const incoming=JSON.parse(e.newValue);if(validHQ(incoming)){hq=incoming;if(loggedIn)renderHQ()}}catch{}}});
if(loggedIn){render();applyHQGate()}
// Back up the added operational records alongside the original directory export.
if(PAGE==='index'){
 const tools=document.querySelector('.data-tools');
 tools.insertAdjacentHTML('beforeend','<hr><p>상담 회차·기관 연결·예약·프로젝트·의뢰·팀닥터 코멘트 별도 백업</p><button class="button" id="hq-export">업무 기록 백업</button><label class="button file-label">업무 기록 복원<input type="file" id="hq-import" accept="application/json"></label>');
 $('hq-export').onclick=()=>{if(!hq)return;const u=URL.createObjectURL(new Blob([JSON.stringify({version:1,hq},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='mps-work-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
 $('hq-import').onchange=async e=>{try{const f=e.target.files[0];if(!f||f.size>5e6)throw Error();const d=JSON.parse(await f.text());if(d.version!==1||!validHQ(d.hq))throw Error();if(confirm('현재 업무 기록을 백업 내용으로 교체할까요?')){hq=d.hq;persistHQ();renderHQ()}}catch{toast('업무 기록 백업 파일을 확인하세요.')}e.target.value=''};
}
if(PAGE==='surveys')document.querySelectorAll('.resource[href]').forEach(a=>{const btn=document.createElement('button');btn.className='button';btn.textContent='양식 주소 복사';btn.onclick=async e=>{e.preventDefault();e.stopPropagation();try{await navigator.clipboard.writeText(a.href);toast('양식 주소를 복사했습니다.')}catch{toast('주소 복사가 지원되지 않습니다. 양식을 열어 주소를 복사하세요.')}};const wrap=document.createElement('div');wrap.className='survey-item';a.before(wrap);wrap.append(a,btn)});

function renderHQReferrals(){if(!$('hq-referrals')||!hq)return;mount('hq-referrals',`<div class="record-list">${hq.referrals.map(r=>`<div><b>${esc(nameFor(r.centerId))} → ${esc(nameFor(r.clinicId))}</b><p>${esc(data.players.find(p=>p.id===r.playerId)?.name||'삭제된 선수')} · ${esc(r.reason)}</p><select data-hq-ref="${esc(r.id)}" aria-label="의뢰 처리 상태">${['본부 접수','본부 검토 중','클리닉 연결 완료'].map(x=>`<option ${x===r.status?'selected':''}>${x}</option>`).join('')}</select></div>`).join('')||'<p class="muted">접수된 의뢰가 없습니다. 센터 샘플콘솔에서 요청을 등록할 수 있습니다.</p>'}</div>`);document.querySelectorAll('[data-hq-ref]').forEach(s=>s.onchange=()=>{hq.referrals.find(r=>r.id===s.dataset.hqRef).status=s.value;persistHQ()})}
