'use strict';
const fields=[...document.querySelectorAll('[data-field]')];
function update(){const scores=[...document.querySelectorAll('.score')],done=scores.filter(x=>x.value!=='');const out=document.querySelector('#score-total');if(out)out.textContent=done.length===10?String(done.reduce((n,e)=>n+Number(e.value),0)):`미완료 (${done.length}/10개 평가)`;}
document.addEventListener('change',update);
document.querySelector('#save').onclick=()=>{const values=Object.fromEntries(fields.map(e=>[e.dataset.field,['checkbox','radio'].includes(e.type)?e.checked:e.tagName==='SELECT'?e.value:e.textContent]));const blob=new Blob([JSON.stringify({version:1,doc:document.body.dataset.doc,values},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`MPS_${document.body.dataset.doc}_${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
document.querySelector('#load').onclick=()=>document.querySelector('#upload').click();
document.querySelector('#upload').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;const data=JSON.parse(await file.text());if(data.doc!==document.body.dataset.doc||data.version!==1||!data.values)throw Error('이 문서와 일치하는 저장 파일이 아닙니다.');const pending=fields.map(f=>{const v=data.values[f.dataset.field];if(v===undefined)throw Error('저장 항목이 누락되었습니다.');if(['checkbox','radio'].includes(f.type)&&typeof v!=='boolean')throw Error('체크값 오류');if(!['checkbox','radio'].includes(f.type)&&typeof v!=='string')throw Error('텍스트값 오류');if(f.tagName==='SELECT'&&![...f.options].some(o=>o.value===v))throw Error('점수 범위 오류');return[f,v];});if(!confirm('현재 작성내용을 저장 파일의 내용으로 바꿀까요?'))return;for(const[f,v]of pending){if(['checkbox','radio'].includes(f.type))f.checked=v;else if(f.tagName==='SELECT')f.value=v;else f.textContent=v;}update();}catch(err){alert('불러오기 실패: '+err.message);}finally{e.target.value='';}};
document.querySelector('#print').onclick=()=>{const bad=[...document.querySelectorAll('.sheet')].filter(s=>s.querySelector('.content').getBoundingClientRect().bottom>s.querySelector('footer').getBoundingClientRect().top-10);document.querySelectorAll('.overflow').forEach(e=>e.classList.remove('overflow'));if(bad.length){bad.forEach(e=>e.classList.add('overflow'));alert('일부 페이지의 작성내용이 인쇄 영역을 넘었습니다. 빨간 테두리 페이지의 내용을 줄이거나 별첨으로 정리한 후 인쇄하세요.');return;}window.print();};
update();
